// Generated by node scripts/build.mjs. Edit src/ files, then rebuild.
const MINUTE_MS = 60_000;
const DAY_MS = 86_400_000;
const DEFAULT_TIMEZONE = "Europe/Moscow";
const MAX_LESSONS = 100;
const formatters = new Map();

export class ScheduleInputError extends Error {
  constructor(message, lineNumber) {
    super(lineNumber ? `Строка ${lineNumber}: ${message}` : message);
    this.name = "ScheduleInputError";
    if (lineNumber) this.lineNumber = lineNumber;
  }
}

const days = new Map([
  ["пн", 1], ["понедельник", 1], ["mon", 1], ["monday", 1], ["1", 1],
  ["вт", 2], ["вторник", 2], ["tue", 2], ["tuesday", 2], ["2", 2],
  ["ср", 3], ["среда", 3], ["wed", 3], ["wednesday", 3], ["3", 3],
  ["чт", 4], ["четверг", 4], ["thu", 4], ["thursday", 4], ["4", 4],
  ["пт", 5], ["пятница", 5], ["fri", 5], ["friday", 5], ["5", 5],
  ["сб", 6], ["суббота", 6], ["sat", 6], ["saturday", 6], ["6", 6],
  ["вс", 7], ["воскресенье", 7], ["sun", 7], ["sunday", 7], ["7", 7],
]);

const weeks = new Map([
  ["all", "all"], ["каждую", "all"], ["каждую неделю", "all"],
  ["все", "all"], ["обе", "all"], ["еженедельно", "all"],
  ["odd", "odd"], ["нечет", "odd"], ["нечетная", "odd"],
  ["нечетная неделя", "odd"], ["нечетную", "odd"],
  ["even", "even"], ["чет", "even"], ["четная", "even"],
  ["четная неделя", "even"], ["четную", "even"],
]);

function alias(value) {
  return value.toLowerCase().replaceAll("ё", "е").replace(/\.$/, "");
}

function normalizedField(value, name, maxLength, lineNumber) {
  const field = value.trim().normalize("NFC").replace(/[ \t]+/g, " ");
  if (!field) throw new ScheduleInputError(`поле «${name}» не может быть пустым.`, lineNumber);
  if (field.length > maxLength) {
    throw new ScheduleInputError(`поле «${name}» должно быть не длиннее ${maxLength} символов.`, lineNumber);
  }
  if (/[\u0000-\u001f\u007f\u2028\u2029]/u.test(field)) {
    throw new ScheduleInputError(`поле «${name}» содержит недопустимые управляющие символы.`, lineNumber);
  }
  return field;
}

function lessonIdentity(lesson) {
  return JSON.stringify([
    lesson.day, lesson.time, lesson.subject, lesson.teacher,
    lesson.room, lesson.location, lesson.week, lesson.english_group || 'all',
  ]);
}

export function parseSchedule(text) {
  if (typeof text !== "string") throw new ScheduleInputError("Пришли расписание текстом.");
  if (text.length > 64_000) throw new ScheduleInputError("Расписание слишком длинное: максимум 64 000 символов.");

  const lessons = [];
  const seen = new Set();
  for (const [index, line] of text.split(/\r\n?|\n/).entries()) {
    if (!line.trim() || line.trimStart().startsWith("#")) continue;
    const lineNumber = index + 1;
    if (lessons.length >= MAX_LESSONS) {
      throw new ScheduleInputError(`можно добавить не больше ${MAX_LESSONS} пар.`, lineNumber);
    }
    const columns = line.split("|");
    if (columns.length < 6 || columns.length > 8) {
      throw new ScheduleInputError("нужны 6 полей через |: день | время | предмет | преподаватель | кабинет | расположение. Седьмое поле — каждую, нечёт или чёт, восьмое — группа английского 1, 2 или 3.", lineNumber);
    }
    const dayText = normalizedField(columns[0], "день", 20, lineNumber);
    const day = days.get(alias(dayText));
    if (!day) throw new ScheduleInputError("неизвестный день. Укажи Пн, Вт, Ср, Чт, Пт, Сб или Вс.", lineNumber);

    const time = normalizedField(columns[1], "время", 5, lineNumber);
    if (!/^(?:[01]\d|2[0-3]):[0-5]\d$/.test(time)) {
      throw new ScheduleInputError("время должно быть в формате ЧЧ:ММ, например 09:00 (от 00:00 до 23:59).", lineNumber);
    }
    const weekText = columns.length >= 7 ? normalizedField(columns[6], "неделя", 30, lineNumber) : "all";
    const week = weeks.get(alias(weekText));
    if (!week) throw new ScheduleInputError("неделя должна быть «каждую», «нечёт» или «чёт». Чётность — по номеру недели ISO.", lineNumber);

    const englishGroupText = columns.length === 8 ? normalizedField(columns[7], "группа английского", 12, lineNumber) : "all";
    const englishGroupAlias = alias(englishGroupText);
    const englishGroup = englishGroupAlias === "все" || englishGroupAlias === "all" || englishGroupAlias === "каждую"
      ? "all" : englishGroupAlias;
    if (!['all', '1', '2', '3'].includes(englishGroup)) {
      throw new ScheduleInputError("группа английского должна быть 1, 2, 3 или все.", lineNumber);
    }

    const lesson = {
      day,
      time,
      subject: normalizedField(columns[2], "предмет", 120, lineNumber),
      teacher: normalizedField(columns[3], "преподаватель", 120, lineNumber),
      room: normalizedField(columns[4], "кабинет", 80, lineNumber),
      location: normalizedField(columns[5], "расположение", 240, lineNumber),
      week,
    };
    if (columns.length === 8) lesson.english_group = englishGroup;
    const identity = lessonIdentity(lesson);
    if (seen.has(identity)) throw new ScheduleInputError("эта пара уже есть в расписании; удали повтор.", lineNumber);
    seen.add(identity);
    lessons.push(lesson);
  }
  if (!lessons.length) throw new ScheduleInputError("Расписание пустое. Добавь хотя бы одну пару.");
  return lessons;
}

export function validateTimezone(value) {
  if (typeof value !== "string" || !value.trim() || value.length > 100) {
    throw new ScheduleInputError("Укажи часовой пояс, например Europe/Moscow.");
  }
  try {
    return new Intl.DateTimeFormat("en", { timeZone: value.trim() }).resolvedOptions().timeZone;
  } catch {
    throw new ScheduleInputError("Неизвестный часовой пояс. Пример: Europe/Moscow.");
  }
}

function formatterFor(timezone) {
  let formatter = formatters.get(timezone);
  if (!formatter) {
    const canonical = validateTimezone(timezone);
    formatter = new Intl.DateTimeFormat("en-GB", {
      timeZone: canonical,
      year: "numeric", month: "2-digit", day: "2-digit",
      hour: "2-digit", minute: "2-digit", second: "2-digit",
      hourCycle: "h23",
    });
    if (formatters.size >= 32) formatters.delete(formatters.keys().next().value);
    formatters.set(timezone, formatter);
  }
  return formatter;
}

function instantParts(date, timezone) {
  const instant = date instanceof Date ? date : new Date(date);
  if (!Number.isFinite(instant.getTime())) throw new ScheduleInputError("Некорректные дата и время.");
  const fields = {};
  for (const { type, value } of formatterFor(timezone).formatToParts(instant)) {
    if (type !== "literal") fields[type] = value;
  }
  return {
    date: `${fields.year.padStart(4, "0")}-${fields.month}-${fields.day}`,
    hour: Number(fields.hour), minute: Number(fields.minute), second: Number(fields.second),
  };
}

function parseDate(dateString) {
  if (typeof dateString !== "string" || !/^\d{4}-\d{2}-\d{2}$/.test(dateString)) {
    throw new ScheduleInputError("Дата должна быть в формате ГГГГ-ММ-ДД.");
  }
  const date = new Date(`${dateString}T00:00:00.000Z`);
  if (!Number.isFinite(date.getTime()) || date.toISOString().slice(0, 10) !== dateString) {
    throw new ScheduleInputError("Такой календарной даты не существует.");
  }
  return date;
}

export function localDateParts(date, timezone = DEFAULT_TIMEZONE) {
  const parts = instantParts(date, timezone);
  return {
    date: parts.date,
    day: parseDate(parts.date).getUTCDay() || 7,
    hour: parts.hour,
    minute: parts.minute,
  };
}

function isoWeekNumber(date) {
  const thursday = new Date(date);
  thursday.setUTCDate(thursday.getUTCDate() + 4 - (thursday.getUTCDay() || 7));
  const yearStart = new Date(thursday);
  yearStart.setUTCMonth(0, 1);
  return Math.ceil(((thursday.getTime() - yearStart.getTime()) / DAY_MS + 1) / 7);
}

export function lessonsForDate(lessons, dateString) {
  const date = parseDate(dateString);
  const day = date.getUTCDay() || 7;
  const parity = isoWeekNumber(date) % 2 ? "odd" : "even";
  return lessons
    .filter(lesson => lesson.day === day && (lesson.week === "all" || lesson.week === parity))
    .sort((a, b) => a.time.localeCompare(b.time) || a.subject.localeCompare(b.subject, "ru"));
}

function offsetsForDate(dateString, timezone) {
  const midday = new Date(`${dateString}T12:00:00.000Z`).getTime();
  const offsets = new Set();
  // Probe either side of a possible offset change, including half-hour DST changes.
  for (const shift of [-36 * 60 * MINUTE_MS, 0, 36 * 60 * MINUTE_MS]) {
    const instant = midday + shift;
    const parts = instantParts(instant, timezone);
    const clockAsUtc = parseDate(parts.date).getTime()
      + parts.hour * 60 * MINUTE_MS + parts.minute * MINUTE_MS + parts.second * 1000;
    offsets.add(clockAsUtc - instant);
  }
  return [...offsets];
}

function localStartAt(dateString, time, timezone, offsets) {
  const [hour, minute] = time.split(":").map(Number);
  const clockAsUtc = parseDate(dateString).getTime() + hour * 60 * MINUTE_MS + minute * MINUTE_MS;
  const matches = offsets.map(offset => clockAsUtc - offset).filter(instant => {
    const parts = instantParts(instant, timezone);
    return parts.date === dateString && parts.hour === hour && parts.minute === minute && parts.second === 0;
  });
  // A skipped DST time has no occurrence; a repeated time uses the first occurrence.
  return matches.length ? Math.min(...matches) : null;
}

function reminderKey(lesson, dateString) {
  let hash = 0xcbf29ce484222325n;
  for (const byte of new TextEncoder().encode(lessonIdentity(lesson))) {
    hash ^= BigInt(byte);
    hash = BigInt.asUintN(64, hash * 0x100000001b3n);
  }
  return `${dateString}:${hash.toString(16).padStart(16, "0")}`;
}

export function reminderCandidates(lessons, settings = {}, now = new Date()) {
  const timezone = settings.timezone ?? DEFAULT_TIMEZONE;
  const leadMinutes = settings.lead_minutes ?? 15;
  if (!Number.isInteger(leadMinutes) || leadMinutes < 1 || leadMinutes > 120) {
    throw new ScheduleInputError("Напоминание можно установить за целое число минут от 1 до 120.");
  }
  const nowMs = now instanceof Date ? now.getTime() : new Date(now).getTime();
  const today = localDateParts(new Date(nowMs), timezone).date;
  const tomorrow = parseDate(today);
  tomorrow.setUTCDate(tomorrow.getUTCDate() + 1);
  const candidates = [];
  for (const date of [today, tomorrow.toISOString().slice(0, 10)]) {
    const scheduled = lessonsForDate(lessons, date);
    if (!scheduled.length) continue;
    const offsets = offsetsForDate(date, timezone);
    for (const lesson of scheduled) {
      const startAt = localStartAt(date, lesson.time, timezone, offsets);
      if (startAt === null) continue;
      const remaining = startAt - nowMs;
      if (remaining > 0 && remaining <= leadMinutes * MINUTE_MS) {
        candidates.push({
          key: reminderKey(lesson, date), lesson, date, startAt,
          minutesUntil: Math.ceil(remaining / MINUTE_MS),
        });
      }
    }
  }
  return candidates.sort((a, b) => a.startAt - b.startAt || a.key.localeCompare(b.key));
}

export function formatReminder(candidate) {
  const { lesson, minutesUntil } = candidate;
  const lastTwo = minutesUntil % 100;
  const last = minutesUntil % 10;
  const unit = lastTwo >= 11 && lastTwo <= 14 ? "минут"
    : last === 1 ? "минуту" : last >= 2 && last <= 4 ? "минуты" : "минут";
  return [
    `🔔 Пара через ${minutesUntil} ${unit} — в ${lesson.time}`,
    `📚 ${lesson.subject}`,
    `👤 Преподаватель: ${lesson.teacher}`,
    `🚪 Иди в кабинет ${lesson.room}`,
    `📍 ${lesson.location}`,
  ].join("\n");
}

// Общие шаблоны групп. Новый пользователь получает копию шаблона при первом
// обращении к боту; после этого его schedule хранится отдельно в user_settings.
//
// Расположение кабинетов в исходной фотографии не указано, поэтому его можно
// заменить прямо здесь или личным импортом через /import.
export const DEFAULT_GROUP_ID = '26-01';

const LOCATION = 'СПбГУГА — корпус уточнить';

export const GROUP_SCHEDULES = Object.freeze({
  '26-01': `
# 1-я неделя в фото соответствует чётной ISO-неделе.
Пн | 09:00 | Общий курс безопасности транспортной деятельности | Преподаватель не указан | к8 | ${LOCATION} | чёт
Пн | 10:45 | Иностранный язык (английский) | Мухтабарова О.И. | к7 | ${LOCATION} | чёт | 1
Пн | 10:45 | Иностранный язык (английский) | Антипова Е.Е. | к7 | ${LOCATION} | чёт | 2
Пн | 10:45 | Иностранный язык (английский) | Яковлева К.М. | к7 | ${LOCATION} | чёт | 3
Пн | 13:00 | Геоинформационные основы навигации | Сарайский Ю.Н. | 301 | ${LOCATION} | чёт
Пн | 15:00 | Введение в специальность | Сатановский М.Ю. | 301 | ${LOCATION} | чёт
Вт | 09:00 | Высшая математика | Черник Т.А. | 352 | ${LOCATION} | чёт
Вт | 10:45 | Механика | Артюк В.Г. | 301 | ${LOCATION} | чёт
Вт | 13:00 | Иностранный язык (английский) | Мухтабарова О.И. | к7 | ${LOCATION} | чёт | 1
Вт | 13:00 | Иностранный язык (английский) | Антипова Е.Е. | к7 | ${LOCATION} | чёт | 2
Вт | 13:00 | Иностранный язык (английский) | Яковлева К.М. | к7 | ${LOCATION} | чёт | 3
Вт | 15:00 | Механика | Артюк В.Г. | 503 | ${LOCATION} | чёт
Ср | 09:00 | Геоинформационные основы навигации | Сарайский Ю.Н. | 304 | ${LOCATION} | чёт
Ср | 10:45 | История России | Ефимова А.В. | 301 | ${LOCATION} | чёт
Ср | 13:00 | Начертательная геометрия и инженерная графика | Ефимова Е.В. | 304 | ${LOCATION} | чёт
Ср | 15:00 | Основы российской государственности | Якубова С.Я. | 301 | ${LOCATION} | чёт
Чт | 10:45 | Основы российской государственности | Якубова С.Я. | 460 | ${LOCATION} | чёт
Чт | 13:00 | История России | Ефимова А.В. | 365 | ${LOCATION} | чёт
Пт | 10:45 | История гражданской авиации | Карпов А.В. | 301 | ${LOCATION} | чёт
Пт | 13:00 | Электротехника и электроника | Сапитов Д.И. | 301 | ${LOCATION} | чёт
Сб | 13:00 | Общефизическая и специальная физическая подготовка | Преподаватель не указан | к9 | ${LOCATION} | чёт
Сб | 15:00 | Общефизическая и специальная физическая подготовка | Преподаватель не указан | к9 | ${LOCATION} | чёт

# 2-я неделя в фото соответствует нечётной ISO-неделе.
Пн | 10:45 | Иностранный язык (английский) | Мухтабарова О.И. | к7 | ${LOCATION} | нечёт | 1
Пн | 10:45 | Иностранный язык (английский) | Антипова Е.Е. | к7 | ${LOCATION} | нечёт | 2
Пн | 10:45 | Иностранный язык (английский) | Яковлева К.М. | к7 | ${LOCATION} | нечёт | 3
Пн | 13:00 | Основы российской государственности | Якубова С.Я. | 301 | ${LOCATION} | нечёт
Вт | 09:00 | Физическая культура и спорт | Преподаватель не указан | к9 | ${LOCATION} | нечёт
Вт | 10:45 | Электротехника и электроника | Сапитов Д.И. | 205 | ${LOCATION} | нечёт
Вт | 13:00 | Высшая математика | Черник Т.А. | 352 | ${LOCATION} | нечёт
Вт | 15:00 | История России | Ефимова А.В. | 301 | ${LOCATION} | нечёт
Ср | 09:00 | История гражданской авиации | Карпов А.В. | 365 | ${LOCATION} | нечёт
Ср | 10:45 | Основы российской государственности | Якубова С.Я. | 475 | ${LOCATION} | нечёт
Ср | 13:00 | Общий курс безопасности транспортной деятельности | Преподаватель не указан | 301 | ${LOCATION} | нечёт
Чт | 09:00 | Высшая математика | Черник Т.А. | 411 | ${LOCATION} | нечёт
Чт | 10:45 | История России | Ефимова А.В. | 365 | ${LOCATION} | нечёт
Чт | 15:00 | Общий курс безопасности транспортной деятельности | Преподаватель не указан | к8 | ${LOCATION} | нечёт
Пт | 09:00 | Геоинформационные основы навигации | Сарайский Ю.Н. | 309 | ${LOCATION} | нечёт
Пт | 10:45 | Иностранный язык (английский) | Мухтабарова О.И. | к7 | ${LOCATION} | нечёт | 1
Пт | 10:45 | Иностранный язык (английский) | Антипова Е.Е. | к7 | ${LOCATION} | нечёт | 2
Пт | 10:45 | Иностранный язык (английский) | Яковлева К.М. | к7 | ${LOCATION} | нечёт | 3
Пт | 13:00 | Начертательная геометрия и инженерная графика | Ефимова Е.В. | 504 | ${LOCATION} | нечёт
Пт | 15:00 | Основы российской государственности | Якубова С.Я. | 475 | ${LOCATION} | нечёт
Сб | 13:00 | Общефизическая и специальная физическая подготовка | Преподаватель не указан | к9 | ${LOCATION} | нечёт
Сб | 15:00 | Общефизическая и специальная физическая подготовка | Преподаватель не указан | к9 | ${LOCATION} | нечёт
`,
});

export function groupScheduleText(groupId = DEFAULT_GROUP_ID) {
  return GROUP_SCHEDULES[String(groupId)] || '';
}

export const DB_SCHEMA = `
CREATE TABLE IF NOT EXISTS settings (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  timezone TEXT NOT NULL DEFAULT 'Europe/Moscow',
  lead_minutes INTEGER NOT NULL DEFAULT 15,
  paused INTEGER NOT NULL DEFAULT 0,
  schedule TEXT NOT NULL DEFAULT '[]'
);
CREATE TABLE IF NOT EXISTS user_settings (
  chat_id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  timezone TEXT NOT NULL DEFAULT 'Europe/Moscow',
  lead_minutes INTEGER NOT NULL DEFAULT 15,
  paused INTEGER NOT NULL DEFAULT 0,
  schedule TEXT NOT NULL DEFAULT '[]',
  english_group TEXT NOT NULL DEFAULT '1',
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS user_settings_active ON user_settings(paused, chat_id);
CREATE TABLE IF NOT EXISTS room_routes (
  room_key TEXT PRIMARY KEY,
  room TEXT NOT NULL,
  directions TEXT NOT NULL,
  updated_at INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS room_routes_room ON room_routes(room);
CREATE TABLE IF NOT EXISTS jobs (
  key TEXT PRIMARY KEY,
  done INTEGER NOT NULL DEFAULT 0,
  applied INTEGER NOT NULL DEFAULT 0,
  lease_until INTEGER NOT NULL,
  lease_owner TEXT NOT NULL,
  expires_at INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS jobs_expiry ON jobs(expires_at);
`;

export const COMMANDS = [
  ['today', 'Пары сегодня'], ['tomorrow', 'Пары завтра'], ['week', 'Всё расписание'],
  ['import', 'Загрузить расписание'], ['settings', 'Настройки'], ['remind', 'За 10 или 15 минут'],
  ['pause', 'Приостановить напоминания'], ['resume', 'Включить напоминания'],
  ['test', 'Проверить сообщение'], ['timezone', 'Часовой пояс'], ['id', 'Мой Telegram ID'],
  ['clear', 'Очистить расписание'], ['group', 'Восстановить расписание группы'],
  ['english', 'Группа английского'], ['table', 'Кабинеты и преподаватели'],
  ['help', 'Инструкция'], ['start', 'Начать'],
].map(([command, description]) => ({ command, description }));

const IMPORT_EXAMPLE = 'Пн | 09:00 | Математика | Иванов И.И. | 305 | Корпус А, 3 этаж\nВт | 10:40 | Физика | Петрова А.С. | 112 | Главный корпус, 1 этаж';
const HELP_TEXT = `Я напомню о паре и подскажу, где кабинет. У каждого пользователя свои расписание и настройки. Для новых пользователей загружен общий шаблон группы ${DEFAULT_GROUP_ID}.\n\nПришли своё расписание одним сообщением, по строке на пару:\n${IMPORT_EXAMPLE}\n\nПоля: день | начало | предмет | преподаватель | кабинет | расположение. Новая загрузка целиком заменяет старую. Можно прислать файл .txt в UTF-8 до 32 КБ.\n\nРасписание повторяется каждую неделю. Необязательное 7-е поле: каждую, чёт или нечёт (номер календарной недели ISO). Для английского можно добавить восьмое поле: группа 1, 2 или 3.\n\n/today — пары сегодня\n/tomorrow — пары завтра\n/week — всё расписание\n/table — таблица «кабинет — преподаватель — предмет»\n/english 1, /english 2 или /english 3 — выбрать группу английского\n/remind 10 или /remind 15 — время напоминания\n/settings — настройки\n/timezone Europe/Moscow — часовой пояс\n/pause и /resume — выключить и включить напоминания\n/test — пример сообщения\n/group — восстановить общий шаблон группы ${DEFAULT_GROUP_ID}\n/clear confirm — удалить только своё расписание\n\nКаждое утро около 07:00 бот присылает расписание на день. Маршруты кабинетов можно заполнить в онлайн-форме по адресу /rooms.`;
const WEEKDAY_NAMES = ['Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб', 'Вс'];
const MAX_TEXT_BYTES = 32768;

export class TelegramError extends Error {
  constructor(code) { super(`Telegram API error ${code}`); this.code = code; }
}

export async function telegramApi(env, method, payload) {
  const transport = env.TELEGRAM_FETCH || fetch;
  let response;
  try {
    response = await transport(`https://api.telegram.org/bot${env.BOT_TOKEN}/${method}`, {
      method: 'POST', headers: { 'content-type': 'application/json' },
      body: JSON.stringify(payload), signal: AbortSignal.timeout(10000),
    });
  } catch { throw new TelegramError('network'); }
  let data;
  try { data = await response.json(); } catch { throw new TelegramError(response.status); }
  if (!response.ok || !data.ok) throw new TelegramError(data.error_code || response.status);
  return data.result;
}

async function sendText(env, chatId, text) {
  // Keep every message below Telegram's 4096-character limit, including long schedules.
  let remaining = text;
  while (remaining.length) {
    let end = Math.min(3500, remaining.length);
    if (end < remaining.length) {
      const newline = remaining.lastIndexOf('\n', end);
      if (newline > 0) end = newline;
      else if (/[\uD800-\uDBFF]/.test(remaining[end - 1])) end--;
    }
    await telegramApi(env, 'sendMessage', { chat_id: chatId, text: remaining.slice(0, end) });
    remaining = remaining.slice(end).replace(/^\n/, '');
  }
}

const schemaPromises = new WeakMap();

function validTelegramId(value) {
  return /^[1-9]\d*$/.test(String(value)) ? String(value) : null;
}

async function ensureUserSchema(env) {
  let promise = schemaPromises.get(env);
  if (!promise) {
    promise = (async () => {
      // This also upgrades an already-connected singleton deployment before its
      // first message after the multi-user version is published.
      await env.DB.batch([
        env.DB.prepare(`CREATE TABLE IF NOT EXISTS user_settings (
          chat_id TEXT PRIMARY KEY,
          user_id TEXT NOT NULL,
          timezone TEXT NOT NULL DEFAULT 'Europe/Moscow',
          lead_minutes INTEGER NOT NULL DEFAULT 15,
          paused INTEGER NOT NULL DEFAULT 0,
          schedule TEXT NOT NULL DEFAULT '[]',
          english_group TEXT NOT NULL DEFAULT '1',
          created_at INTEGER NOT NULL,
          updated_at INTEGER NOT NULL
        )`),
        env.DB.prepare('CREATE INDEX IF NOT EXISTS user_settings_active ON user_settings(paused, chat_id)'),
        env.DB.prepare(`CREATE TABLE IF NOT EXISTS room_routes (
          room_key TEXT PRIMARY KEY,
          room TEXT NOT NULL,
          directions TEXT NOT NULL,
          updated_at INTEGER NOT NULL
        )`),
        env.DB.prepare('CREATE INDEX IF NOT EXISTS room_routes_room ON room_routes(room)'),
      ]);
      // Existing deployments have user_settings without english_group. D1 does
      // not support IF NOT EXISTS for ADD COLUMN, so inspect the schema first.
      const columns = (await env.DB.prepare('PRAGMA table_info(user_settings)').all()).results || [];
      if (!columns.some(column => column.name === 'english_group')) {
        await env.DB.prepare("ALTER TABLE user_settings ADD COLUMN english_group TEXT NOT NULL DEFAULT '1'").run();
      }
    })().catch(error => {
      schemaPromises.delete(env);
      throw error;
    });
    schemaPromises.set(env, promise);
  }
  await promise;
}

async function migrateLegacySettings(env, chatId) {
  const ownerId = validTelegramId(env.OWNER_ID);
  if (!ownerId || String(chatId) !== ownerId) return;
  const legacy = await env.DB.prepare('SELECT timezone, lead_minutes, paused, schedule FROM settings WHERE id = 1').first();
  if (!legacy) return;
  const now = Date.now();
  await env.DB.prepare(`INSERT OR IGNORE INTO user_settings
    (chat_id, user_id, timezone, lead_minutes, paused, schedule, created_at, updated_at)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?)`)
    .bind(ownerId, ownerId, legacy.timezone, legacy.lead_minutes, legacy.paused, legacy.schedule, now, now).run();
}

function configuredGroup(env) {
  return String(env.DEFAULT_GROUP || DEFAULT_GROUP_ID).trim() || DEFAULT_GROUP_ID;
}

function defaultScheduleJson(env) {
  const group = configuredGroup(env);
  const text = groupScheduleText(group);
  if (!text) return '[]';
  try {
    return JSON.stringify(parseSchedule(text));
  } catch (error) {
    // A malformed built-in template must not prevent a new user from starting
    // the bot. The template is covered by tests and can be repaired separately.
    console.error(`Invalid built-in schedule template for group ${group}.`, error);
    return '[]';
  }
}

async function readSettings(env, chatId, userId = chatId) {
  await ensureUserSchema(env);
  const timezone = validateTimezone(env.DEFAULT_TIMEZONE || 'Europe/Moscow');
  const normalizedChatId = String(chatId);
  const normalizedUserId = String(userId);
  await migrateLegacySettings(env, normalizedChatId);
  const now = Date.now();
  const inserted = await env.DB.prepare(`INSERT OR IGNORE INTO user_settings
    (chat_id, user_id, timezone, schedule, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?)`)
    .bind(normalizedChatId, normalizedUserId, timezone, defaultScheduleJson(env), now, now).run();
  const row = await env.DB.prepare('SELECT * FROM user_settings WHERE chat_id = ?').bind(normalizedChatId).first();
  return { ...row, lessons: JSON.parse(row.schedule), isNew: Number(inserted?.meta?.changes || 0) > 0 };
}

async function claimJob(env, key, now, lifetime) {
  const owner = crypto.randomUUID();
  const row = await env.DB.prepare(`INSERT INTO jobs (key, lease_until, lease_owner, expires_at)
    VALUES (?, ?, ?, ?) ON CONFLICT(key) DO UPDATE SET
    lease_until = excluded.lease_until, lease_owner = excluded.lease_owner
    WHERE jobs.done = 0 AND jobs.lease_until <= ? RETURNING key`)
    .bind(key, now + 90000, owner, now + lifetime, now).first();
  return row ? owner : null;
}

async function finishJob(env, key, owner) {
  await env.DB.prepare('UPDATE jobs SET done = 1 WHERE key = ? AND lease_owner = ?').bind(key, owner).run();
}

async function releaseJob(env, key, owner) {
  await env.DB.prepare('UPDATE jobs SET lease_until = 0 WHERE key = ? AND lease_owner = ?').bind(key, owner).run();
}

async function applySetting(env, chatId, field, value) {
  if (!['timezone', 'lead_minutes', 'paused', 'schedule', 'english_group'].includes(field)) throw new Error('Unknown setting');
  const { key, lease } = env.UPDATE_JOB;
  // Persist the setting and its update receipt together. A retried reply must never
  // reapply an old import or undo a later /resume, /pause, or setting change.
  await env.DB.batch([
    env.DB.prepare(`UPDATE user_settings SET ${field} = ?, updated_at = ? WHERE chat_id = ?
      AND EXISTS (SELECT 1 FROM jobs WHERE key = ? AND lease_owner = ? AND applied = 0)`)
      .bind(value, Date.now(), String(chatId), key, lease),
    env.DB.prepare('UPDATE jobs SET applied = 1 WHERE key = ? AND lease_owner = ?').bind(key, lease),
  ]);
}

function roomKey(room) {
  return String(room ?? '').trim().replace(/\s+/g, ' ').toLocaleLowerCase('ru-RU');
}

async function readRoomRoutes(env) {
  await ensureUserSchema(env);
  const rows = (await env.DB.prepare('SELECT room_key, room, directions FROM room_routes ORDER BY room_key').all()).results || [];
  return new Map(rows.map(row => [row.room_key, row]));
}

function withRoomRoutes(lessons, routes) {
  return lessons.map(lesson => {
    const route = routes.get(roomKey(lesson.room));
    return route ? { ...lesson, location: route.directions, room_route: true } : lesson;
  });
}

function userLessonsForDate(settings, date, routes = new Map()) {
  const englishGroup = String(settings.english_group || '1');
  const lessons = lessonsForDate(settings.lessons, date).filter(lesson =>
    !lesson.english_group || lesson.english_group === 'all' || englishGroup === 'all' || lesson.english_group === englishGroup,
  );
  return withRoomRoutes(lessons, routes);
}

function userWeeklyLessons(settings, routes = new Map()) {
  const englishGroup = String(settings.english_group || '1');
  return withRoomRoutes(settings.lessons.filter(lesson =>
    !lesson.english_group || lesson.english_group === 'all' || englishGroup === 'all' || lesson.english_group === englishGroup,
  ), routes);
}

function roomTableText(lessons) {
  const seen = new Set();
  const rows = [];
  for (const lesson of lessons) {
    const key = [lesson.room, lesson.teacher, lesson.subject, lesson.english_group || 'all'].join('\u0000');
    if (seen.has(key)) continue;
    seen.add(key);
    const group = lesson.english_group && lesson.english_group !== 'all' ? ` (английский, группа ${lesson.english_group})` : '';
    rows.push(`🚪 ${lesson.room} — 👨‍🏫 ${lesson.teacher} — 📚 ${lesson.subject}${group}`);
  }
  return rows.sort((a, b) => a.localeCompare(b, 'ru')).join('\n');
}

function dailyScheduleText(settings, date, lessons) {
  const header = `☀️ Расписание на сегодня\n${date} · ${settings.timezone}`;
  if (!lessons.length) return `${header}\n\nПар сегодня нет.`;
  return `${header}\n\n${lessons.map(lesson => displayLesson(lesson)).join('\n\n')}`;
}

function plusDays(date, amount) {
  const value = new Date(`${date}T12:00:00Z`);
  value.setUTCDate(value.getUTCDate() + amount);
  return value.toISOString().slice(0, 10);
}

function displayLesson(lesson, showDay = false) {
  const parity = lesson.week === 'odd' ? ' · нечётная неделя ISO' : lesson.week === 'even' ? ' · чётная неделя ISO' : '';
  const group = lesson.english_group && lesson.english_group !== 'all' ? ` · английский, группа ${lesson.english_group}` : '';
  return `${showDay ? WEEKDAY_NAMES[lesson.day - 1] + ' ' : ''}${lesson.time} — ${lesson.subject}${group}${parity}\n👨‍🏫 ${lesson.teacher}\n🚪 Кабинет ${lesson.room}\n📍 ${lesson.location}`;
}

async function importText(env, chatId, text) {
  const lessons = parseSchedule(text);
  await applySetting(env, chatId, 'schedule', JSON.stringify(lessons));
  const settings = await readSettings(env, chatId);
  await sendText(env, chatId, `Загрузка обработана. Сейчас в расписании пар: ${settings.lessons.length}.\nВремя: ${settings.timezone}. Напоминание за ${settings.lead_minutes} мин.\n${settings.paused ? '⏸ Напоминания на паузе. Включить: /resume' : '🔔 Напоминания включены.'}\nПроверь расписание: /week`);
}

async function limitedText(response, limit = MAX_TEXT_BYTES) {
  if (Number(response.headers.get('content-length') || 0) > limit) throw new ScheduleInputError('Файл или сообщение слишком большое (максимум 32 КБ).');
  if (!response.body) return '';
  const reader = response.body.getReader();
  const chunks = [];
  let length = 0;
  for (;;) {
    const { done, value } = await reader.read();
    if (done) break;
    length += value.length;
    if (length > limit) { await reader.cancel(); throw new ScheduleInputError('Файл или сообщение слишком большое (максимум 32 КБ).'); }
    chunks.push(value);
  }
  const bytes = new Uint8Array(length);
  let offset = 0;
  for (const chunk of chunks) { bytes.set(chunk, offset); offset += chunk.length; }
  try { return new TextDecoder('utf-8', { fatal: true }).decode(bytes); }
  catch { throw new ScheduleInputError('Сохрани текстовый файл в кодировке UTF-8.'); }
}

async function documentText(env, document) {
  if (!/\.txt$/i.test(document.file_name || '')) throw new ScheduleInputError('Поддерживается файл .txt в UTF-8 или текст сообщением. Фото, PDF и Excel пока не читаю.');
  if (document.file_size > MAX_TEXT_BYTES) throw new ScheduleInputError('Файл слишком большой: максимум 32 КБ.');
  const file = await telegramApi(env, 'getFile', { file_id: document.file_id });
  if (!/^[a-zA-Z0-9_./-]+$/.test(file.file_path || '')) throw new TelegramError('file');
  let response;
  try {
    response = await (env.TELEGRAM_FETCH || fetch)(`https://api.telegram.org/file/bot${env.BOT_TOKEN}/${file.file_path}`, { signal: AbortSignal.timeout(10000) });
  } catch { throw new TelegramError('network'); }
  if (!response.ok) throw new TelegramError(response.status);
  return limitedText(response);
}

async function processMessage(env, message) {
  const chatId = String(message.chat.id);
  const userId = String(message.from.id);
  const text = (message.text || '').trim();
  const match = text.match(/^\/([a-z_]+)(?:@[a-zA-Z0-9_]+)?(?:\s+([\s\S]*))?$/i);
  const command = match?.[1].toLowerCase();
  const argument = match?.[2]?.trim() || '';
  if (command === 'id') {
    await sendText(env, chatId, `Твой Telegram ID: ${userId}\nБот поддерживает отдельные расписание и настройки для каждого пользователя. Отправь /start, чтобы начать.`);
    return;
  }
  const settings = await readSettings(env, chatId, userId);
  const roomRoutes = await readRoomRoutes(env);
  if (message.document) {
    await importText(env, chatId, await documentText(env, message.document));
    return;
  }
  if (!command && text.includes('|')) { await importText(env, chatId, text); return; }
  switch (command) {
    case 'start': case 'help':
      await sendText(env, chatId, `${HELP_TEXT}${command === 'start' && settings.isNew
        ? `\n\n✅ Шаблон группы ${configuredGroup(env)} загружен. Выбери свою подгруппу английского: /english 1, /english 2 или /english 3.`
        : ''}`); break;
    case 'import':
      if (argument) await importText(env, chatId, argument);
      else await sendText(env, chatId, `Пришли расписание одним сообщением или файлом .txt:\n\n${IMPORT_EXAMPLE}\n\nНовая загрузка полностью заменит старое расписание.`);
      break;
    case 'settings':
      await sendText(env, chatId, `Часовой пояс: ${settings.timezone}\nНапоминание: за ${settings.lead_minutes} мин.\nАнглийский: группа ${settings.english_group === 'all' ? 'все' : settings.english_group}\nПар в расписании: ${settings.lessons.length}\nУтреннее расписание: около 07:00\nСостояние: ${settings.paused ? '⏸ пауза' : '🔔 включены'}\n\n/remind 10 или /remind 15\n/english 1, /english 2 или /english 3\n/timezone Europe/Moscow\n/pause · /resume`); break;
    case 'remind':
      if (!['10', '15'].includes(argument)) { await sendText(env, chatId, 'Выбери: /remind 10 или /remind 15'); break; }
      await applySetting(env, chatId, 'lead_minutes', Number(argument));
      await sendText(env, chatId, `Буду напоминать за ${argument} минут до пары.`); break;
    case 'timezone': {
      if (!argument) { await sendText(env, chatId, `Сейчас: ${settings.timezone}. Изменить: /timezone Europe/Moscow`); break; }
      const timezone = validateTimezone(argument);
      await applySetting(env, chatId, 'timezone', timezone);
      await sendText(env, chatId, `Часовой пояс: ${timezone}. Время пар теперь считается по нему.`); break;
    }
    case 'english': {
      if (!['1', '2', '3', 'all', 'все'].includes(argument.toLowerCase())) {
        await sendText(env, chatId, 'Выбери группу английского: /english 1, /english 2 или /english 3. /english all покажет все три группы.');
        break;
      }
      const englishGroup = ['all', 'все'].includes(argument.toLowerCase()) ? 'all' : argument;
      await applySetting(env, chatId, 'english_group', englishGroup);
      await sendText(env, chatId, `Выбрана группа английского: ${englishGroup === 'all' ? 'все три' : englishGroup}. Проверь /today или /table.`);
      break;
    }
    case 'pause': case 'resume':
      await applySetting(env, chatId, 'paused', command === 'pause' ? 1 : 0);
      await sendText(env, chatId, command === 'pause' ? '⏸ Напоминания на паузе. Включить: /resume' : '🔔 Напоминания включены.'); break;
    case 'clear':
      if (argument !== 'confirm') { await sendText(env, chatId, 'Для удаления всего расписания отправь /clear confirm'); break; }
      await applySetting(env, chatId, 'schedule', '[]');
      await sendText(env, chatId, 'Расписание удалено. Пришли новое, когда будет нужно.'); break;
    case 'group': {
      if (argument && argument !== configuredGroup(env)) {
        await sendText(env, chatId, `Доступен общий шаблон группы ${configuredGroup(env)}. Отправь /group без аргумента.`);
        break;
      }
      const schedule = defaultScheduleJson(env);
      if (schedule === '[]') {
        await sendText(env, chatId, `Шаблон группы ${configuredGroup(env)} пока не настроен.`);
        break;
      }
      await applySetting(env, chatId, 'schedule', schedule);
      await sendText(env, chatId, `Расписание группы ${configuredGroup(env)} восстановлено. Английский: группа ${settings.english_group === 'all' ? 'все' : settings.english_group}. Проверь /table и /today.`);
      break;
    }
    case 'today': case 'tomorrow': {
      const today = localDateParts(new Date(), settings.timezone).date;
      const date = command === 'tomorrow' ? plusDays(today, 1) : today;
      const lessons = userLessonsForDate(settings, date, roomRoutes);
      await sendText(env, chatId, `${command === 'today' ? 'Сегодня' : 'Завтра'}, ${date} (${settings.timezone})\n\n${lessons.length ? lessons.map(l => displayLesson(l)).join('\n\n') : 'Пар нет.'}`); break;
    }
    case 'week':
      {
        const lessons = userWeeklyLessons(settings, roomRoutes);
        await sendText(env, chatId, lessons.length
        ? `Расписание (${settings.timezone})\n\n${[...lessons].sort((a, b) => a.day - b.day || a.time.localeCompare(b.time)).map(l => displayLesson(l, true)).join('\n\n')}`
        : 'Расписание пока пустое. Загрузить: /import'); break;
    }
    case 'table': {
      // The table is an inspection view: show all three English variants even
      // when the personal daily schedule is filtered to one selected group.
      const table = roomTableText(withRoomRoutes(settings.lessons, roomRoutes));
      await sendText(env, chatId, table ? `Таблица распознанного расписания\n\nКабинет — преподаватель — предмет\n\n${table}\n\nМаршруты кабинетов можно заполнить на странице Worker с окончанием /rooms.` : 'Таблица пока пуста. Загрузить расписание: /import');
      break;
    }
    case 'test':
      await sendText(env, chatId, '✅ Тест: бот может отправлять тебе сообщения.\n\nПример напоминания:\n⏰ Через 15 минут, в 09:00 — Математика\n👨‍🏫 Иванов И.И.\n🚪 Идёшь в кабинет 305\n📍 Корпус А, 3 этаж, налево от лестницы\n\nЭто пример. Проверить автоматическое напоминание можно, добавив пару на 16 минут позже текущего времени.'); break;
    default:
      await sendText(env, chatId, 'Пришли расписание текстом или .txt. Формат и команды: /help');
  }
}

export async function handleUpdate(update, env) {
  const message = update.message;
  if (!Number.isSafeInteger(update.update_id) || !message?.from?.id || message.chat?.type !== 'private') return;
  // Every private chat is an independent account. Group chats are rejected above
  // so one user's schedule can never be exposed to a group or another user.
  const key = `update:${update.update_id}`;
  const now = Date.now();
  const lease = await claimJob(env, key, now, 7 * 86400000);
  if (!lease) {
    const existing = await env.DB.prepare('SELECT done FROM jobs WHERE key = ?').bind(key).first();
    if (!existing?.done) throw new Error('Update processing is in progress');
    return;
  }
  try {
    try {
      const receipt = await env.DB.prepare('SELECT applied FROM jobs WHERE key = ?').bind(key).first();
      if (receipt.applied) await sendText(env, message.chat.id, 'Эта команда уже была выполнена. Текущее расписание: /week. Настройки: /settings.');
      else await processMessage({ ...env, UPDATE_JOB: { key, lease } }, message);
    }
    catch (error) {
      if (error instanceof ScheduleInputError) await sendText(env, message.chat.id, `Не удалось загрузить настройки или расписание: ${error.message}\nСтарые данные сохранены.`);
      else throw error;
    }
    await finishJob(env, key, lease);
  } catch (error) {
    // Telegram may retry a webhook: the lease prevents simultaneous processing.
    if (error instanceof TelegramError && error.code === 403) {
      await env.DB.prepare('UPDATE user_settings SET paused = 1, updated_at = ? WHERE chat_id = ?')
        .bind(Date.now(), String(message.chat.id)).run();
      await finishJob(env, key, lease);
      return;
    }
    await releaseJob(env, key, lease);
    throw error;
  }
}

async function runMorningDigests(env, rows, routes, now) {
  for (const row of rows) {
    let settings;
    try {
      settings = { ...row, lessons: JSON.parse(row.schedule) };
    } catch {
      console.error('Skipping a user with invalid schedule data for morning digest.');
      continue;
    }
    const local = localDateParts(now, settings.timezone);
    // Cron runs every minute. A short window tolerates a delayed invocation
    // while the per-day jobs key still guarantees exactly one digest.
    if (local.hour !== 7 || local.minute > 4) continue;
    const key = `daily:${row.chat_id}:${local.date}`;
    const lease = await claimJob(env, key, now.getTime(), 2 * 86400000);
    if (!lease) continue;
    try {
      const lessons = userLessonsForDate(settings, local.date, routes);
      await sendText(env, String(row.chat_id), dailyScheduleText(settings, local.date, lessons));
      await finishJob(env, key, lease);
    } catch (error) {
      if (error instanceof TelegramError && error.code === 403) {
        await env.DB.prepare('UPDATE user_settings SET paused = 1, updated_at = ? WHERE chat_id = ?')
          .bind(Date.now(), String(row.chat_id)).run();
        await finishJob(env, key, lease);
      } else {
        await releaseJob(env, key, lease);
        console.error('Morning schedule delivery failed; will retry during the 07:00 window.');
      }
    }
  }
}

export async function runReminders(env, now = new Date()) {
  const started = Date.now();
  const currentTime = () => now.getTime() + Math.max(0, Date.now() - started);
  await ensureUserSchema(env);
  // Preserve the old singleton schedule when OWNER_ID is still configured.
  await migrateLegacySettings(env, validTelegramId(env.OWNER_ID));
  if (now.getUTCMinutes() === 0) await env.DB.prepare('DELETE FROM jobs WHERE expires_at < ?').bind(now.getTime()).run();
  const rows = (await env.DB.prepare('SELECT * FROM user_settings WHERE paused = 0').all()).results || [];
  const roomRoutes = await readRoomRoutes(env);
  await runMorningDigests(env, rows, roomRoutes, now);
  for (const row of rows) {
    let settings;
    try {
      settings = { ...row, lessons: JSON.parse(row.schedule) };
    } catch {
      console.error('Skipping a user with invalid schedule data.');
      continue;
    }
    settings.lessons = userWeeklyLessons(settings, roomRoutes);
    const candidates = reminderCandidates(settings.lessons, settings, now);
    let blocked = false;
    for (const candidate of candidates) {
      if (candidate.startAt <= currentTime()) continue;
      const chatId = String(row.chat_id);
      const key = `reminder:${chatId}:${candidate.key}`;
      const lease = await claimJob(env, key, currentTime(), 14 * 86400000);
      if (!lease) continue;
      try {
        // Sending earlier reminders can take time. Recheck before each network request.
        const remaining = candidate.startAt - currentTime();
        if (remaining <= 0) { await finishJob(env, key, lease); continue; }
        await sendText(env, chatId, formatReminder({ ...candidate, minutesUntil: Math.ceil(remaining / 60000) }));
        await finishJob(env, key, lease);
      } catch (error) {
        if (error instanceof TelegramError && error.code === 403) {
          await env.DB.prepare('UPDATE user_settings SET paused = 1, updated_at = ? WHERE chat_id = ?')
            .bind(Date.now(), chatId).run();
          await finishJob(env, key, lease);
          blocked = true;
          break;
        }
        await releaseJob(env, key, lease);
        // A later tick retries while the class has not started. Do not log token-bearing URLs.
        console.error('Reminder delivery failed; will retry before class starts.');
      }
    }
    if (blocked) continue;
  }
}

function secretMatches(actual, expected) {
  if (!expected || !actual || actual.length !== expected.length) return false;
  let difference = 0;
  for (let i = 0; i < actual.length; i++) difference |= actual.charCodeAt(i) ^ expected.charCodeAt(i);
  return difference === 0;
}

const SETUP_PAGE = `<!doctype html><html lang="ru"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Подключить бота</title>
<style>body{font:17px/1.6 system-ui;background:#f4f7fc;color:#17243a;max-width:580px;margin:8vh auto;padding:24px}main{background:white;padding:32px;border-radius:20px}input,button{box-sizing:border-box;font:inherit;width:100%;padding:12px;margin-top:12px;border-radius:9px;border:1px solid #b3bfd1}button{background:#2262ce;color:white;cursor:pointer}pre{white-space:pre-wrap;font:inherit}small{color:#52617a}</style>
<main><h1>Подключить Telegram-бота</h1><p>Введи WEBHOOK_SECRET, который ты сохранил в секретах Worker. Токен BotFather сюда вводить не нужно.</p>
<form id="form"><input id="secret" type="password" autocomplete="off" placeholder="WEBHOOK_SECRET" required minlength="32"><button id="connect" type="submit">Подключить</button><button id="status" type="button">Проверить подключение</button></form><pre id="result" aria-live="polite"></pre><small>После подключения каждый пользователь может открыть бота в личном чате и отправить /start. Расписание и настройки отдельные для каждого пользователя. OWNER_ID нужен только для необязательной миграции старого личного расписания. Проверка каждую минуту включается отдельно в настройках Cron Trigger.</small></main>
<script>const form=document.getElementById('form'),secret=document.getElementById('secret'),result=document.getElementById('result');async function request(action){result.textContent='Подожди…';try{const r=await fetch('/setup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({secret:secret.value,action})});const d=await r.json();result.textContent=d.message;}catch{result.textContent='Не удалось подключиться. Попробуй ещё раз.'}}form.addEventListener('submit',e=>{e.preventDefault();request('connect')});document.getElementById('status').addEventListener('click',()=>request('status'));</script></html>`;

const ROOMS_PAGE = `<!doctype html><html lang="ru"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Маршруты кабинетов</title>
<style>body{font:17px/1.55 system-ui;background:#f4f7fc;color:#17243a;max-width:780px;margin:5vh auto;padding:20px}main{background:#fff;padding:28px;border-radius:20px;box-shadow:0 8px 30px #17243a12}input,textarea,button{box-sizing:border-box;font:inherit;width:100%;padding:11px;margin-top:10px;border-radius:9px;border:1px solid #b3bfd1}textarea{min-height:120px;resize:vertical}button{background:#2262ce;color:#fff;cursor:pointer}table{width:100%;border-collapse:collapse;margin-top:20px}th,td{padding:9px;border-bottom:1px solid #d9e0ea;text-align:left;vertical-align:top}small{color:#52617a}#result{white-space:pre-wrap;margin-top:14px}</style>
<main><h1>Маршруты кабинетов</h1><p>Заполни, как пройти к каждому кабинету. Эти подсказки будут подставляться в утреннее расписание, /today и напоминания.</p>
<label>WEBHOOK_SECRET<input id="secret" type="password" autocomplete="off" placeholder="Секрет Worker" required></label>
<form id="route"><label>Кабинет<input id="room" maxlength="80" placeholder="например, 305" required></label><label>Как пройти<textarea id="directions" maxlength="1000" placeholder="Главный корпус, 3 этаж, направо от лестницы"></textarea></label><button type="submit">Сохранить маршрут</button></form>
<button id="refresh" type="button">Показать сохранённые маршруты</button><div id="result" aria-live="polite"></div><small>Секрет используется только для управления этой формой и не сохраняется в браузере.</small></main>
<script>const secret=document.getElementById('secret'),room=document.getElementById('room'),directions=document.getElementById('directions'),result=document.getElementById('result');async function api(action,extra={}){result.textContent='Подожди…';try{const r=await fetch('/rooms',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({secret:secret.value,action,...extra})});const d=await r.json();result.textContent=d.message||'';if(d.routes){const rows=d.routes.map(x=>'<tr><td></td><td></td></tr>');const table=document.createElement('table');table.innerHTML='<thead><tr><th>Кабинет</th><th>Как пройти</th><th></th></tr></thead><tbody></tbody>';const body=table.querySelector('tbody');d.routes.forEach(x=>{const tr=document.createElement('tr');const r=document.createElement('td');r.textContent=x.room;const v=document.createElement('td');v.textContent=x.directions;const c=document.createElement('td');const b=document.createElement('button');b.textContent='Изменить';b.type='button';b.onclick=()=>{room.value=x.room;directions.value=x.directions;window.scrollTo({top:0,behavior:'smooth'});};c.append(b);tr.append(r,v,c);body.append(tr)});result.append(table)}}catch{result.textContent='Не удалось подключиться. Проверь адрес Worker и секрет.'}}document.getElementById('route').addEventListener('submit',e=>{e.preventDefault();api('save',{room:room.value,directions:directions.value})});document.getElementById('refresh').addEventListener('click',()=>api('list'));</script></html>`;

async function saveRoomRoute(env, room, directions) {
  const normalizedRoom = String(room || '').trim().replace(/[\u0000-\u001f\u007f]/g, '');
  const normalizedDirections = String(directions || '').trim().replace(/[\u0000-\u001f\u007f]/g, '');
  if (!normalizedRoom || normalizedRoom.length > 80) throw new ScheduleInputError('Укажи кабинет длиной от 1 до 80 символов.');
  if (!normalizedDirections || normalizedDirections.length > 1000) throw new ScheduleInputError('Опиши маршрут длиной от 1 до 1000 символов.');
  await ensureUserSchema(env);
  await env.DB.prepare(`INSERT INTO room_routes (room_key, room, directions, updated_at) VALUES (?, ?, ?, ?)
    ON CONFLICT(room_key) DO UPDATE SET room = excluded.room, directions = excluded.directions, updated_at = excluded.updated_at`)
    .bind(roomKey(normalizedRoom), normalizedRoom, normalizedDirections, Date.now()).run();
}

async function roomsResponse(env, body) {
  if (!['list', 'save'].includes(body.action)) return jsonMessage('Неизвестное действие формы.', 400);
  if (body.action === 'save') await saveRoomRoute(env, body.room, body.directions);
  const routes = [...(await readRoomRoutes(env)).values()].map(({ room_key, room, directions }) => ({ room_key, room, directions }));
  return Response.json({ message: body.action === 'save' ? 'Маршрут сохранён.' : `Сохранённых маршрутов: ${routes.length}.`, routes }, { headers: { 'cache-control': 'no-store' } });
}

function jsonMessage(message, status = 200) {
  return Response.json({ message }, { status, headers: { 'cache-control': 'no-store' } });
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    if (request.method === 'GET' && (url.pathname === '/' || url.pathname === '/health')) {
      return new Response('Telegram class reminder bot. Setup: /setup', { headers: { 'content-type': 'text/plain; charset=utf-8' } });
    }
    if (request.method === 'GET' && url.pathname === '/setup') {
      return new Response(SETUP_PAGE, { headers: { 'content-type': 'text/html; charset=utf-8', 'cache-control': 'no-store', 'referrer-policy': 'no-referrer', 'x-frame-options': 'DENY', 'content-security-policy': "default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; connect-src 'self'; base-uri 'none'; form-action 'self'; frame-ancestors 'none'" } });
    }
    if (request.method === 'GET' && url.pathname === '/rooms') {
      return new Response(ROOMS_PAGE, { headers: { 'content-type': 'text/html; charset=utf-8', 'cache-control': 'no-store', 'referrer-policy': 'no-referrer', 'x-frame-options': 'DENY', 'content-security-policy': "default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; connect-src 'self'; base-uri 'none'; form-action 'self'; frame-ancestors 'none'" } });
    }
    if (request.method !== 'POST' || !['/telegram', '/setup', '/rooms'].includes(url.pathname)) return new Response('Not found', { status: 404 });
    if (!env.WEBHOOK_SECRET || !env.DB) return jsonMessage('Добавь WEBHOOK_SECRET и привязку базы D1 с именем DB.', 503);
    if (url.pathname !== '/rooms' && !env.BOT_TOKEN) return jsonMessage('Добавь BOT_TOKEN, WEBHOOK_SECRET и привязку базы D1 с именем DB.', 503);
    if (url.pathname === '/telegram' && !secretMatches(request.headers.get('X-Telegram-Bot-Api-Secret-Token'), env.WEBHOOK_SECRET)) return new Response('Forbidden', { status: 403 });
    let body;
    try { body = JSON.parse(await limitedText(request)); if (!body || typeof body !== 'object' || Array.isArray(body)) throw new Error(); }
    catch { return jsonMessage('Некорректное или слишком большое сообщение.', 400); }
    if (url.pathname === '/rooms') {
      if (typeof body.secret !== 'string' || !secretMatches(body.secret, env.WEBHOOK_SECRET)) return jsonMessage('Неверный WEBHOOK_SECRET.', 403);
      if (!/^[a-zA-Z0-9_-]{32,256}$/.test(env.WEBHOOK_SECRET) || env.WEBHOOK_SECRET.startsWith('REPLACE_')) return jsonMessage('Задай WEBHOOK_SECRET: 32–256 случайных латинских букв, цифр, _ или -.', 400);
      try { return await roomsResponse(env, body); }
      catch (error) {
        if (error instanceof ScheduleInputError) return jsonMessage(error.message, 400);
        console.error('Room route form failed.');
        return jsonMessage('Не удалось сохранить маршрут кабинета.', 500);
      }
    }
    if (url.pathname === '/setup') {
      if (typeof body.secret !== 'string' || !secretMatches(body.secret, env.WEBHOOK_SECRET)) return jsonMessage('Неверный WEBHOOK_SECRET.', 403);
      if (!/^[a-zA-Z0-9_-]{32,256}$/.test(env.WEBHOOK_SECRET) || env.WEBHOOK_SECRET.startsWith('REPLACE_')) return jsonMessage('Задай WEBHOOK_SECRET: 32–256 случайных латинских букв, цифр, _ или -.', 400);
      try {
        if (body.action !== 'status') {
          await env.DB.batch(DB_SCHEMA.split(';').map(sql => sql.trim()).filter(Boolean).map(sql => env.DB.prepare(sql)));
          await ensureUserSchema(env);
          await migrateLegacySettings(env, validTelegramId(env.OWNER_ID));
          await telegramApi(env, 'setWebhook', { url: `${url.origin}/telegram`, secret_token: env.WEBHOOK_SECRET, allowed_updates: ['message'], max_connections: 1 });
          await telegramApi(env, 'setMyCommands', { commands: COMMANDS });
        }
        const info = await telegramApi(env, 'getWebhookInfo', {});
        const correct = info.url === `${url.origin}/telegram`;
        return jsonMessage(`${correct ? '✅ Telegram подключён.' : '⚠ Telegram пока не подключён к этому адресу.'}\nОжидают обработки: ${info.pending_update_count || 0}.${info.last_error_date ? '\nTelegram сообщал об ошибке доставки. Если очередь растёт, проверь настройки и подключи заново.' : ''}\nСледующий шаг: отправь /start в личном чате с ботом. Каждый пользователь получит своё расписание и настройки. Cron Trigger должен быть * * * * *.`);
      } catch { return jsonMessage('Ошибка подключения. Проверь токен BotFather, базу D1 и её привязку DB. Секреты в журнал не записываются.', 502); }
    }
    try { await handleUpdate(body, env); return new Response('OK'); }
    catch { console.error('Webhook processing failed.'); return new Response('Retry later', { status: 500 }); }
  },
  async scheduled(_controller, env) {
    // Use actual execution time to avoid stale reminders after delayed cron invocations.
    await runReminders(env, new Date());
  },
};
