import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { DB_SCHEMA } from '../src/worker.mjs';

const root = new URL('../', import.meta.url);
const schedule = await readFile(new URL('src/schedule.mjs', root), 'utf8');
const groupSchedule = await readFile(new URL('src/group-schedule.mjs', root), 'utf8');
const worker = await readFile(new URL('src/worker.mjs', root), 'utf8');
// All three modules use standard Web APIs. Inline the local imports so the
// generated file can be pasted into the Cloudflare dashboard as one file.
let standalone = worker.replace(/import\s*\{[^}]+\}\s*from\s*['"]\.\/schedule\.mjs['"];?\s*/, '');
standalone = standalone.replace(/import\s*\{[^}]+\}\s*from\s*['"]\.\/group-schedule\.mjs['"];?\s*/, '');
if (standalone === worker) throw new Error('Worker imports were not found; update the bundler.');
await writeFile(new URL('cloudflare-worker.mjs', root),
  '// Generated by node scripts/build.mjs. Edit src/ files, then rebuild.\n'
  + schedule + '\n' + groupSchedule + '\n' + standalone);
await writeFile(new URL('schema.sql', root), DB_SCHEMA.trim() + '\n');
console.log('Готов файл для Cloudflare: ' + fileURLToPath(new URL('cloudflare-worker.mjs', root)));
